tolgee:
  file-storage:
    fs-data-path: /data
  authentication:
    enabled: false
spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:h2:${tolgee.file-storage.fs-data-path}/db.h2
    username: sa
    password: password
  liquibase:
    change-log: classpath:db/changelog/schema.xml
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
sentry:
  dsn: ${tolgee.sentry.server-dsn:}
