services:
  db:
    image: postgres:18.0
    volumes:
      - ../build/db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    image: tolgee/tolgee
    ports:
      - ${exposePort}:8080
    env_file:
      - .env
    depends_on:
      - "db"
  smtp:
    image: namshi/smtp
