spring:
  autoconfigure:
    exclude: org.redisson.spring.starter.RedissonAutoConfiguration, org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        order_by:
          default_null_ordering: first
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        dialect: io.tolgee.dialects.postgres.CustomPostgreSQLDialect
        types:
          print:
            banner: false
        enhancer:
          enableLazyInitialization: true
          enableDirtyTracking: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
tolgee:
  authentication:
    enabled: false
  postgres-autostart:
    enabled: true
  cache:
    enabled: true
    use-redis: false
    default-ttl: 1200000
server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json"
    min-response-size: 1024
  error:
    include-exception: false
    include-stacktrace: never
sentry:
  dsn: ${tolgee.sentry.server-dsn:}
  traces-sample-rate: ${tolgee.sentry.traces-sample-rate:}
management:
  health:
    ldap:
      enabled: false
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

