version: '3'
services:
  app:
    container_name: tolgee_e2e
    image: tolgee/tolgee:local
    ports:
      - 8201:8201
      - 8091:8091
    environment:
      - spring.profiles.active=docker,e2e
      - tolgee.smtp.host=fakesmtp
      - tolgee.smtp.port=1025
      - tolgee.frontend-url=http://localhost:8201
      # tests go brrrr but then get 429'd and no longer go brrrr
      - tolgee.rate-limits.global-limits=false
      - tolgee.rate-limits.endpoint-limits=false
      - tolgee.rate-limits.authentication-limits=false
  fakesmtp:
    image: reachfive/fake-smtp-server:0.8.1
    ports:
      - "21025:1025"
      - "21080:1080"
volumes:
  e2e-db-data:
